### ISSUE TITLE
Build Project

### ISSUE THREAD

**Issue by antoinemoussy** [HuangRunHua/ScreenSaver#3]

**Comment by antoinemoussy** [comment]
Hi! I am not a Xcode specialist. I just try to build your project but I have errors about import Player line.
Maybe it is an easy stuff but I don't know how to do.
Steps are missing into How To?

I will appreciate help I don't know how to discuss with you

**Comment by HuangRunHua** [comment]
> Hi! I am not a Xcode specialist. I just try to build your project but I have errors about import Player line.
> Maybe it is an easy stuff but I don't know how to do.
> Steps are missing into How To?
> 
> I will appreciate help I don't know how to discuss with you

Hi there, you need to build the Player framework first, Pods-ScreenSaver second, and build ScreenSaver final.
