### ISSUE TITLE
macOS 

### ISSUE THREAD

**Issue by antoinemoussy** [HuangRunHua/ScreenSaver#6]
Hi!
I try to use your good work to create a macOS app (Mac Catalyst).
Everything works good but video is played into a frame.

Do you have an idea to play it fullscreen automatically? (toggle in fullscreen is working but I try to play video fullscreen when the app launch)

Thanks for your job very useful

**Comment by HuangRunHua** [comment]
Well, for macOS it's better to create ScreenSaver app (under macOS environment selection when launching Xcode). For the basic detail of how to use ScreenSaver template please follow the instruction: [How to Make a Custom Screensaver for Mac OS X](https://betterprogramming.pub/how-to-make-a-custom-screensaver-for-mac-os-x-7e1650c13bd8)
